# Generated by Django 4.0.4 on 2022-07-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My House', max_length=100)),
                ('address', models.CharField(default='9 Bruce Street', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Fun Event', max_length=100)),
                ('creation_Date', models.DateField(auto_now_add=True)),
                ('start_datetime', models.DateTimeField(default='2022-12-07 12:00:00')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_dev.venue')),
            ],
        ),
    ]
