# Generated by Django 4.0.4 on 2022-07-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_dev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creation_Date',
            new_name='creation_date',
        ),
    ]
